In [2]:
from dask.distributed import Client

client = Client("tcp://192.168.2.100:8786")
client

<Client: 'tcp://192.168.2.100:8786' processes=3 threads=6, memory=60.00 GB>

In [3]:
import dask.array as da

from sklearn.datasets import  make_classification

from dpyacl.core.misc import split


In [14]:
_split_count = 10
_feature_num = 1000
_label_num = 3
_instance_num = 100000

_X, _y = make_classification(n_samples=_instance_num, n_features=_feature_num, n_informative=2*_label_num, n_redundant=_label_num,
                             n_repeated=0, n_classes=_label_num, n_clusters_per_class=_label_num, weights=None,
                             flip_y=0.01,
                             class_sep=1.0,
                             hypercube=True, shift=0.0, scale=1.0, shuffle=True, random_state=None)

_X = da.from_array(_X, chunks="16MB")
_y = da.from_array(_y, chunks="16MB")

_X

dask.array<array, shape=(100000, 1000), dtype=float64, chunksize=(2000, 1000), chunktype=numpy.ndarray>

In [17]:
%%time
train_idx, test_idx, label_idx, unlabel_idx = split(X=_X,
                                                    y=_X,
                                                    all_class=True,
                                                    split_count=_split_count,
                                                    test_ratio=0.3,
                                                    initial_label_rate=0.05)

train_idx, test_idx, label_idx, unlabel_idx



CPU times: user 2.36 s, sys: 4.72 s, total: 7.08 s
Wall time: 23.8 s


([array([34123, 65724, 56383, ..., 97536, 33200, 45901]),
  array([69364, 59224, 48604, ..., 47205, 96480,  5658]),
  array([65976, 67267, 23770, ..., 66547, 12146, 90502]),
  array([41213, 38752, 84086, ..., 64345,   224, 25987]),
  array([62562, 60178, 42272, ..., 28148, 73391, 77133]),
  array([26150, 52606, 82748, ..., 30045, 95182,  5412]),
  array([33118, 54417, 79323, ...,   434, 36341, 74708]),
  array([ 1838, 52092, 10399, ..., 47804, 97504, 62139]),
  array([93192, 15499, 27486, ..., 73245, 97678, 55450]),
  array([ 2528,  6065, 11823, ..., 17610, 89688, 92033])],
 [array([71585, 35957, 53828, ..., 60920, 21003, 93161]),
  array([22078, 17129,  5370, ..., 55457, 21323, 38618]),
  array([18214, 73446, 52599, ..., 71535, 87660, 81696]),
  array([30522, 20566, 20528, ..., 57128,  4166, 32409]),
  array([60461, 38911, 38394, ..., 18017, 73991, 80020]),
  array([94590, 72338, 97502, ..., 66915, 44369, 40122]),
  array([17115, 77576, 88236, ..., 11505, 98074, 30496]),
  array([ 850